# Jekyll configuration
name: seroseverny
description: Thoughts on software engineering

url: https://seroseverny.github.io/

baseurl: ''

github: ''
gitlab: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'G-HEL67TG70D'

# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: true

# Set this to your public isso URL to enable comments via isso. Set to '' to disable isso.
isso: ''

# Set this to your disqus shortname to enable comments via disqus. Set to '' to disable disqus.
disqus: ''

permalink: /:year/:month/:title
paginate: 3

highlighter: rouge
markdown: kramdown
gems: ['jekyll-paginate']

exclude: ['README.md', 'LICENSE']
